apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
  namespace: next-me
  labels:
    app: eureka-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      imagePullSecrets:
        - name: ghcr-cred
      containers:
        - name: eureka-server
          image: ghcr.io/sparta-next-me/eureka-server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3150
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  namespace: next-me
spec:
  selector:
    app: eureka-server
  ports:
    - name: http
      port: 3150
      targetPort: 3150
  type: ClusterIP
