apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
  namespace: next-me
  labels:
    app: eureka-server
spec:
  replicas: 2  # 고가용성을 위해 2대로 증설 (app, infra 노드에 나눠짐)
  # [추가] 롤링 업데이트 상세 전략
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1 # 업데이트 중 동시에 사용할 수 없는 파드 최대 개수
      maxSurge: 1       # 업데이트 중 기준 replicas보다 더 생성될 수 있는 파드 최대 개수
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      # [추가] 두 노드(app, infra)에 골고루 배포되도록 강제하는 설정
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - eureka-server
              topologyKey: "kubernetes.io/hostname"
      imagePullSecrets:
        - name: ghcr-cred
      containers:
        - name: eureka-server
          image: ghcr.io/sparta-next-me/eureka-server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3150 # 컨테이너 내부 포트는 유지
              # [핵심 추가] 이 설정이 있어야 진짜 무중단 배포가 됩니다
          readinessProbe:
            httpGet:
              path: /actuator/health # 스프링 부트 헬스체크 경로
              port: 3150
            initialDelaySeconds: 40  # 부팅 시간을 고려해 40초 후부터 검사 시작
            periodSeconds: 10        # 10초마다 확인
            failureThreshold: 3      # 3번 실패하면 준비 안 된 것으로 간주
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  namespace: next-me
spec:
  selector:
    app: eureka-server
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 3151       # 쿠버네티스 내부 서비스 포트 (도커 3150과 충돌 방지)
      targetPort: 3150 # 컨테이너 내부 3150으로 전달
      nodePort: 30151  #  외부 IP:30151로 접속 가능